name: Run Crossfit .com WOD Crawler

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Description'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Load Repository Files
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Crawler
      run: |
        python main.py
      env:
        Github_Access_Token: \$
